openapi: 3.0.0
info:
  title: BeamFi
  version: 1.0.0
servers:
  - url: http://meeting-api-dev.beamfi.app
  - url: http://meeting-api.beamfi.app
paths:
  /api/signature:
    post:
      tags:
        - default
      summary: Zoom Meeting API Signature - Prod
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                meetingNumber: 123456
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
