name: BeamFi Dev Topup Cycles

on:
  workflow_dispatch:
  schedule:
    - cron: "00 22 * * *"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.13.0"
      - name: Setup Canister Ids
        run: cp canister_ids_dev.json canister_ids.json
      - name: Install DFX
        run: echo y | sh -ci "$(curl -fsSL https://internetcomputer.org/install.sh)"
        env:
          DFX_VERSION: 0.11.2
      - name: Add DFX identity and wallets
        run: ./scripts/add-ic-identity.sh
        env:
          DFX_IDENTITY: ${{ secrets.DFX_IDENTITY }}
          DFX_WALLETS: ${{ secrets.DFX_WALLETS }}
      - name: Top up Canisters' Cycles
        run: npm run topup
      - name: Show success mesg
        run: echo Congratulations! The topup is successful.
